### ISSUE TITLE
Convert the design manual to asciidoc

### ISSUE THREAD

**Issue by ari** [ishgroup/onCourseDocs#1]
As an experiment with using a simpler to edit format, convert docbook to asciidoc for the design manual. pandoc might be the best tool.

We don't need to product PDF output for the manual, only HTML. Let's use this gradle plugin https://asciidoctor.github.io/asciidoctor-gradle-plugin/development-3.x/user-guide/ as the way to launch the tooling.

**Comment by ari** [comment]
I pushed a new branch asciidoc to evaluate the docbookrx conversion tool.

**Comment by chintankotadia** [comment]
@ari: Thanks and I have setup everything in my local. I would like to understand what do I exactly need on this task? Some insights would be quiet helpful.

**Comment by ari** [comment]
Done
